### ISSUE TITLE
Feature Addition: Implement a navbar for the anti-ragging page

### ISSUE THREAD

**Issue by sanchitkalra** [Ashish-AVS/SWD-BPHC-Frontend#7]

**Comment by ChiragJaju** [comment]
Can you provide more information on this?

**Comment by joshianirudh17** [comment]
Can I resolve this issue?

**Comment by Ashish-AVS** [comment]
The navbar that is present right now, is only being rendered at the home page we want that navbar to be rendered on the non authenticated routes as well which include the anti-ragging page.

**Comment by Ashish-AVS** [comment]
> Can I resolve this issue?

Sure go ahead
